(package-initialize)

(defun load-layer (p)
  (load (locate-user-emacs-file (concat "layers/" p)) nil :nomessage))

(add-to-list 'load-path "~/.emacs.d/layers/")
(load-layer "util.el")
(load-layer "better-defaults.el")
(load-layer "package-init.el")
(load-layer "main-init.el")
(load-layer "evil-init.el")
(load-layer "general-init.el")
(load-layer "ivy-init.el")
(load-layer "web-dev.el")

(desktop-load-default)
(desktop-read)

;; Emacs autogenerated stuff

(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(custom-safe-themes
   (quote
    ("a6e5edd129bc48c9540ab6ed4a76a2e4e0da6359e981a3ec0bffbeb4416d4cc9" "611e38c2deae6dcda8c5ac9dd903a356c5de5b62477469133c89b2785eb7a14d" "365d9553de0e0d658af60cff7b8f891ca185a2d7ba3fc6d29aadba69f5194c7f" "6f11ad991da959fa8de046f7f8271b22d3a97ee7b6eca62c81d5a917790a45d9" "b81bfd85aed18e4341dbf4d461ed42d75ec78820a60ce86730fc17fc949389b2" "bffa9739ce0752a37d9b1eee78fc00ba159748f50dc328af4be661484848e476" default)))
 '(package-selected-packages
   (quote
    (spacemacs-theme flycheck doom-themes evil general which-key counsel ivy use-package))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
