(setq delete-old-versions -1)
(setq version-control t)
(setq vc-make-backup-files t)
(setq backup-directory-alist `(("." . "~/.emacs.d/backups")))
(setq vc-follow-symlinks t)
(setq auto-save-file-name-transforms '((".*" "~/.emacs.d/auto-save-list/" t)))
(setq inhibit-startup-screen t)
(setq ring-bell-function 'ignore)
(setq coding-system-for-read 'utf-8)
(setq coding-system-for-write 'utf-8)
(setq sentence-end-double-space nil)
(setq default-fill-column 80)
(setq initial-scratch-message "")
(setq default-frame-alist '((font . "Source Code Pro-9")))
(setq mouse-yank-at-point t)
(setq evil-want-fine-undo nil)

(setq tab-width 2)
(setq-default evil-shift-width 2)
(setq javascript-indent-level 2)
(setq js-indent-level 2)
(setq js2-basic-offset 2)
(setq typescript-indent-level 2)
(setq web-mode-markup-indent-offset 2)
(setq web-mode-css-indent-offset 2)
(setq web-mode-code-indent-offset 2)
(setq css-indent-offset 2)

(setq browse-url-browser-function 'browse-url-generic
      browse-url-generic-program "google-chrome-stable")
;; No triple ESC stuff
(define-key key-translation-map (kbd "ESC") (kbd "C-g"))

(desktop-save-mode t)
(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)
(window-divider-mode t)
(global-linum-mode t)
(global-auto-revert-mode t)
